export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL = ''
export const SITE_NAME = 'AndrewEnsley.com'
export const SITE_TAG_LINE = 'Leader / Developer / Musician'
export const AUTHOR_NAME = 'Andrew Ensley'
export const AUTHOR_PICTURE = 'https://www.gravatar.com/avatar/88387a69eef0b3caea7f4e8920c1ca08?s=48'
